import { QuizConfig } from "./QuizTypes";

export const alphabetQuiz: QuizConfig = {
title: "Sign Language Alphabet",
questions: [
{
id: 1,
image: require("./alphabets/Alphabets/A.png"),
      choices: [
        { id: "A", label: "A" },
        { id: "B", label: "B" },
        { id: "C", label: "C" },
        { id: "D", label: "D" },
      ],
      correctChoiceId: "A",
    },
    {
      id: 2,
      image: require("./alphabets/Alphabets/B.png"),
      choices: [
        { id: "A", label: "A" },
        { id: "B", label: "B" },
        { id: "C", label: "C" },
        { id: "D", label: "D" },
      ],
      correctChoiceId: "B",
    },
    {
      id: 3,
      image: require("./alphabets/Alphabets/C.png"),
      choices: [
        { id: "A", label: "A" },
        { id: "B", label: "B" },
        { id: "C", label: "C" },
        { id: "D", label: "D" },
      ],
      correctChoiceId: "C",
    },
    {
      id: 4,
      image: require("./alphabets/Alphabets/D.png"),
      choices: [
        { id: "A", label: "A" },
        { id: "B", label: "B" },
        { id: "C", label: "C" },
        { id: "D", label: "D" },
      ],
      correctChoiceId: "D",
    },
    {
      id: 5,
      image: require("./alphabets/Alphabets/E.png"),
      choices: [
        { id: "E", label: "E" },
        { id: "F", label: "F" },
        { id: "G", label: "G" },
        { id: "H", label: "H" },
      ],
      correctChoiceId: "E",
    },
    {
      id: 6,
      image: require("./alphabets/Alphabets/F.png"),
      choices: [
        { id: "E", label: "E" },
        { id: "F", label: "F" },
        { id: "G", label: "G" },
        { id: "H", label: "H" },
      ],
      correctChoiceId: "F",
    },
    {
      id: 7,
      image: require("./alphabets/Alphabets/G.png"),
      choices: [
        { id: "E", label: "E" },
        { id: "F", label: "F" },
        { id: "G", label: "G" },
        { id: "H", label: "H" },
      ],
      correctChoiceId: "G",
    },
    {
      id: 8,
      image: require("./alphabets/Alphabets/H.png"),
      choices: [
        { id: "E", label: "E" },
        { id: "F", label: "F" },
        { id: "G", label: "G" },
        { id: "H", label: "H" },
      ],
      correctChoiceId: "H",
    },
    {
      id: 9,
      image: require("./alphabets/Alphabets/I.png"),
      choices: [
        { id: "I", label: "I" },
        { id: "J", label: "J" },
        { id: "K", label: "K" },
        { id: "L", label: "L" },
      ],
      correctChoiceId: "I",
    },
    {
      id: 10,
      image: require("./alphabets/Alphabets/J.png"),
      choices: [
        { id: "I", label: "I" },
        { id: "J", label: "J" },
        { id: "K", label: "K" },
        { id: "L", label: "L" },
      ],
      correctChoiceId: "J",
    },
    {
      id: 11,
      image: require("./alphabets/Alphabets/K.png"),
      choices: [
        { id: "I", label: "I" },
        { id: "J", label: "J" },
        { id: "K", label: "K" },
        { id: "L", label: "L" },
      ],
      correctChoiceId: "K",
    },
    {
      id: 12,
      image: require("./alphabets/Alphabets/L.png"),
      choices: [
        { id: "I", label: "I" },
        { id: "J", label: "J" },
        { id: "K", label: "K" },
        { id: "L", label: "L" },
      ],
      correctChoiceId: "L",
    },
    {
      id: 13,
      image: require("./alphabets/Alphabets/M.png"),
      choices: [
        { id: "M", label: "M" },
        { id: "N", label: "N" },
        { id: "O", label: "O" },
        { id: "P", label: "P" },
      ],
      correctChoiceId: "M",
    },
    {
      id: 14,
      image: require("./alphabets/Alphabets/N.png"),
      choices: [
        { id: "M", label: "M" },
        { id: "N", label: "N" },
        { id: "O", label: "O" },
        { id: "P", label: "P" },
      ],
      correctChoiceId: "N",
    },
    {
      id: 15,
      image: require("./alphabets/Alphabets/O.png"),
      choices: [
        { id: "M", label: "M" },
        { id: "N", label: "N" },
        { id: "O", label: "O" },
        { id: "P", label: "P" },
      ],
      correctChoiceId: "O",
    },
    {
      id: 16,
      image: require("./alphabets/Alphabets/P.png"),
      choices: [
        { id: "M", label: "M" },
        { id: "N", label: "N" },
        { id: "O", label: "O" },
        { id: "P", label: "P" },
      ],
      correctChoiceId: "P",
    },
    {
      id: 17,
      image: require("./alphabets/Alphabets/Q.png"),
      choices: [
        { id: "Q", label: "Q" },
        { id: "R", label: "R" },
        { id: "S", label: "S" },
        { id: "T", label: "T" },
      ],
      correctChoiceId: "Q",
    },
    {
      id: 18,
      image: require("./alphabets/Alphabets/R.png"),
      choices: [
        { id: "Q", label: "Q" },
        { id: "R", label: "R" },
        { id: "S", label: "S" },
        { id: "T", label: "T" },
      ],
      correctChoiceId: "R",
    },
    {
      id: 19,
      image: require("./alphabets/Alphabets/S.png"),
      choices: [
        { id: "Q", label: "Q" },
        { id: "R", label: "R" },
        { id: "S", label: "S" },
        { id: "T", label: "T" },
      ],
      correctChoiceId: "S",
    },
    {
      id: 20,
      image: require("./alphabets/Alphabets/T.png"),
      choices: [
        { id: "Q", label: "Q" },
        { id: "R", label: "R" },
        { id: "S", label: "S" },
        { id: "T", label: "T" },
      ],
      correctChoiceId: "T",
    },
    {
      id: 21,
      image: require("./alphabets/Alphabets/U.png"),
      choices: [
        { id: "U", label: "U" },
        { id: "V", label: "V" },
        { id: "W", label: "W" },
        { id: "X", label: "X" },
      ],
      correctChoiceId: "U",
    },
    {
      id: 22,
      image: require("./alphabets/Alphabets/V.png"),
      choices: [
        { id: "U", label: "U" },
        { id: "V", label: "V" },
        { id: "W", label: "W" },
        { id: "X", label: "X" },
      ],
      correctChoiceId: "V",
    },
    {
      id: 23,
      image: require("./alphabets/Alphabets/W.png"),
      choices: [
        { id: "U", label: "U" },
        { id: "V", label: "V" },
        { id: "W", label: "W" },
        { id: "X", label: "X" },
      ],
      correctChoiceId: "W",
    },
    {
      id: 24,
      image: require("./alphabets/Alphabets/X.png"),
      choices: [
        { id: "U", label: "U" },
        { id: "V", label: "V" },
        { id: "W", label: "W" },
        { id: "X", label: "X" },
      ],
      correctChoiceId: "X",
    },
    {
      id: 25,
      image: require("./alphabets/Alphabets/Y.png"),
      choices: [
        { id: "Y", label: "Y" },
        { id: "Z", label: "Z" },
        { id: "A", label: "A" },
        { id: "B", label: "B" },
      ],
      correctChoiceId: "Y",
    },
    {
      id: 26,
      image: require("./alphabets/Alphabets/Z.png"),
      choices: [
        { id: "Y", label: "Y" },
        { id: "Z", label: "Z" },
        { id: "A", label: "A" },
        { id: "B", label: "B" },
      ],
      correctChoiceId: "Z",
    },
  ],
};
