export const alphabetData = [
{ letter: 'A', image: require('./alphabets/Alphabets/A.png'), text: 'Apple' },
  { letter: 'B', image: require('./alphabets/Alphabets/B.png'), text: 'Ball' },
  { letter: 'C', image: require('./alphabets/Alphabets/C.png'), text: 'Cat' },
  { letter: 'D', image: require('./alphabets/Alphabets/D.png'), text: 'Dog' },
  { letter: 'E', image: require('./alphabets/Alphabets/E.png'), text: 'Elephant' },
  { letter: 'F', image: require('./alphabets/Alphabets/F.png'), text: 'Fish' },
  { letter: 'G', image: require('./alphabets/Alphabets/G.png'), text: 'Giraffe' },
  { letter: 'H', image: require('./alphabets/Alphabets/H.png'), text: 'Hat' },
  { letter: 'I', image: require('./alphabets/Alphabets/I.png'), text: 'Ice cream' },
  { letter: 'J', image: require('./alphabets/Alphabets/J.png'), text: 'Juice' },
  { letter: 'K', image: require('./alphabets/Alphabets/K.png'), text: 'Kite' },
  { letter: 'L', image: require('./alphabets/Alphabets/L.png'), text: 'Lion' },
  { letter: 'M', image: require('./alphabets/Alphabets/M.png'), text: 'Monkey' },
  { letter: 'N', image: require('./alphabets/Alphabets/N.png'), text: 'Nest' },
  { letter: 'O', image: require('./alphabets/Alphabets/O.png'), text: 'Orange' },
  { letter: 'P', image: require('./alphabets/Alphabets/P.png'), text: 'Pig' },
  { letter: 'Q', image: require('./alphabets/Alphabets/Q.png'), text: 'Queen' },
  { letter: 'R', image: require('./alphabets/Alphabets/R.png'), text: 'Rabbit' },
  { letter: 'S', image: require('./alphabets/Alphabets/S.png'), text: 'Sun' },
  { letter: 'T', image: require('./alphabets/Alphabets/T.png'), text: 'Tiger' },
  { letter: 'U', image: require('./alphabets/Alphabets/U.png'), text: 'Umbrella' },
  { letter: 'V', image: require('./alphabets/Alphabets/V.png'), text: 'Violin' },
  { letter: 'W', image: require('./alphabets/Alphabets/W.png'), text: 'Whale' },
  { letter: 'X', image: require('./alphabets/Alphabets/X.png'), text: 'Xylophone' },
  { letter: 'Y', image: require('./alphabets/Alphabets/Y.png'), text: 'Yacht' },
  { letter: 'Z', image: require('./alphabets/Alphabets/Z.png'), text: 'Zebra' },
];
